= A List of Things To Do In & Near Clemson, SC
:published_at: 2016-07-27
:hp-tags: Clemson


College is a ton of fun and all about going out and making memories. However, sometimes it can be hard to find places to create those memories. There are travel sites that list things to do but they might favor paid listings, seem severely cluttered, or contain outdated information. I know that I have always wanted a list of things to do around Clemson so that when bored my friends and I would have something to quickly refer back to.

I've created a spreadsheet that lists a decent amount of things to do in Clemson and the surrounding areas (Anderson, Greenville, etc.). There are some things on here I'm sure you'll be familiar with and some that may come as a surprise. The list will be ever-changing and growing as I find new things worth checking out. As of right now, there's "Fun Places", "Clemson Bucket List", "Misc. Outdoors", "Food", and "Hiking", though this could definitely change.

Here's the list:

<embed spreadsheet here>


https://docs.google.com/spreadsheets/d/1_NcWvoQCSMrZUHVz26lu6AklIF_Dl7z60cfVcfX6Qm0/pub?output=xlsx[(If you feel like downloading as a spreadsheet, click here.) ]

If you have any questions/comments/anything you want added, feel free to send me an email at matthew@matthewtrombley.com. This is meant to be a resource for all Clemson students (and even people that live around Clemson). Bookmark it, share it, take advantage of it, whatever you feel like doing. The more people that contribute the more we can help make it a resource for students to use for years and years.

Enjoy!